export const PRESET_CITIES: Record<string, { name: string; slug: string; sort_order: number }[]> = {
  aichi: [
    { name: "名古屋市", slug: "nagoya", sort_order: 1 },
    { name: "豊橋市", slug: "toyohashi", sort_order: 2 },
    { name: "岡崎市", slug: "okazaki", sort_order: 3 },
    { name: "一宮市", slug: "ichinomiya", sort_order: 4 },
    { name: "春日井市", slug: "kasugai", sort_order: 5 },
    { name: "豊田市", slug: "toyota", sort_order: 6 },
    { name: "安城市", slug: "anjo", sort_order: 7 },
    { name: "刈谷市", slug: "kariya", sort_order: 8 },
    { name: "西尾市", slug: "nishio", sort_order: 9 },
    { name: "小牧市", slug: "komaki", sort_order: 10 },
    { name: "稲沢市", slug: "inazawa", sort_order: 11 },
    { name: "東海市", slug: "tokai", sort_order: 12 },
    { name: "大府市", slug: "obu", sort_order: 13 },
    { name: "知多市", slug: "chita", sort_order: 14 },
    { name: "長久手市", slug: "nagakute", sort_order: 15 },
    { name: "日進市", slug: "nisshin", sort_order: 16 },
    { name: "清須市", slug: "kiyosu", sort_order: 17 },
    { name: "北名古屋市", slug: "kitanagoya", sort_order: 18 },
    { name: "弥富市", slug: "yatomi", sort_order: 19 },
    { name: "みよし市", slug: "miyoshi", sort_order: 20 },
    { name: "あま市", slug: "ama", sort_order: 21 },
    { name: "豊明市", slug: "toyoake", sort_order: 22 },
    { name: "田原市", slug: "tahara", sort_order: 23 },
    { name: "愛西市", slug: "aisai", sort_order: 24 },
    { name: "尾張旭市", slug: "owariasahi", sort_order: 25 },
    { name: "高浜市", slug: "takahama", sort_order: 26 },
    { name: "岩倉市", slug: "iwakura", sort_order: 27 },
    { name: "知立市", slug: "chiryu", sort_order: 28 },
    { name: "江南市", slug: "konan", sort_order: 29 },
    { name: "新城市", slug: "shinshiro", sort_order: 30 },
  ],
  gifu: [
    { name: "岐阜市", slug: "gifu", sort_order: 1 },
    { name: "大垣市", slug: "ogaki", sort_order: 2 },
    { name: "各務原市", slug: "kakamigahara", sort_order: 3 },
    { name: "可児市", slug: "kani", sort_order: 4 },
    { name: "多治見市", slug: "tajimi", sort_order: 5 },
    { name: "関市", slug: "seki", sort_order: 6 },
    { name: "美濃加茂市", slug: "minokamo", sort_order: 7 },
    { name: "土岐市", slug: "toki", sort_order: 8 },
    { name: "高山市", slug: "takayama", sort_order: 9 },
    { name: "中津川市", slug: "nakatsugawa", sort_order: 10 },
    { name: "恵那市", slug: "ena", sort_order: 11 },
    { name: "瑞浪市", slug: "mizunami", sort_order: 12 },
    { name: "羽島市", slug: "hashima", sort_order: 13 },
    { name: "海津市", slug: "kaizu", sort_order: 14 },
    { name: "山県市", slug: "yamagata", sort_order: 15 },
    { name: "瑞穂市", slug: "mizuho", sort_order: 16 },
    { name: "本巣市", slug: "motosu", sort_order: 17 },
    { name: "郡上市", slug: "gujo", sort_order: 18 },
    { name: "下呂市", slug: "gero", sort_order: 19 },
    { name: "飛騨市", slug: "hida", sort_order: 20 },
  ],
  mie: [
    { name: "津市", slug: "tsu", sort_order: 1 },
    { name: "四日市市", slug: "yokkaichi", sort_order: 2 },
    { name: "鈴鹿市", slug: "suzuka", sort_order: 3 },
    { name: "松阪市", slug: "matsusaka", sort_order: 4 },
    { name: "伊勢市", slug: "ise", sort_order: 5 },
    { name: "桑名市", slug: "kuwana", sort_order: 6 },
    { name: "伊賀市", slug: "iga", sort_order: 7 },
    { name: "名張市", slug: "nabari", sort_order: 8 },
    { name: "亀山市", slug: "kameyama", sort_order: 9 },
    { name: "志摩市", slug: "shima", sort_order: 10 },
    { name: "いなべ市", slug: "inabe", sort_order: 11 },
    { name: "熊野市", slug: "kumano", sort_order: 12 },
    { name: "尾鷲市", slug: "owase", sort_order: 13 },
    { name: "鳥羽市", slug: "toba", sort_order: 14 },
  ],
  shizuoka: [
    { name: "静岡市", slug: "shizuoka", sort_order: 1 },
    { name: "浜松市", slug: "hamamatsu", sort_order: 2 },
    { name: "沼津市", slug: "numazu", sort_order: 3 },
    { name: "富士市", slug: "fuji", sort_order: 4 },
    { name: "磐田市", slug: "iwata", sort_order: 5 },
    { name: "焼津市", slug: "yaizu", sort_order: 6 },
    { name: "掛川市", slug: "kakegawa", sort_order: 7 },
    { name: "藤枝市", slug: "fujieda", sort_order: 8 },
    { name: "富士宮市", slug: "fujinomiya", sort_order: 9 },
    { name: "三島市", slug: "mishima", sort_order: 10 },
    { name: "御殿場市", slug: "gotemba", sort_order: 11 },
    { name: "袋井市", slug: "fukuroi", sort_order: 12 },
    { name: "熱海市", slug: "atami", sort_order: 13 },
    { name: "伊東市", slug: "ito", sort_order: 14 },
    { name: "島田市", slug: "shimada", sort_order: 15 },
    { name: "裾野市", slug: "susono", sort_order: 16 },
    { name: "湖西市", slug: "kosai", sort_order: 17 },
    { name: "下田市", slug: "shimoda", sort_order: 18 },
    { name: "伊豆市", slug: "izu", sort_order: 19 },
    { name: "御前崎市", slug: "omaezaki", sort_order: 20 },
    { name: "菊川市", slug: "kikugawa", sort_order: 21 },
    { name: "伊豆の国市", slug: "izunokuni", sort_order: 22 },
    { name: "牧之原市", slug: "makinohara", sort_order: 23 },
  ],
};
