// 郡 → 市スラッグ のマッピング（郡部の町村の駅を近隣の市に割り当てる）
export const GUN_TO_CITY: Record<string, string> = {
  // ─── 愛知県 ───
  "aichi:愛知郡": "nisshin",
  "aichi:西春日井郡": "kitanagoya",
  "aichi:丹羽郡": "konan",
  "aichi:知多郡": "chita",
  "aichi:海部郡": "ama",
  "aichi:幡豆郡": "nishio",
  "aichi:額田郡": "okazaki",
  "aichi:北設楽郡": "shinshiro",
  "aichi:南設楽郡": "shinshiro",
  "aichi:東加茂郡": "toyota",
  "aichi:西加茂郡": "toyota",
  "aichi:宝飯郡": "toyokawa",
  "aichi:渥美郡": "tahara",
  "aichi:碧海郡": "anjo",
  // ─── 岐阜県 ───
  "gifu:羽島郡": "hashima",
  "gifu:海津郡": "kaizu",
  "gifu:養老郡": "ogaki",
  "gifu:不破郡": "ogaki",
  "gifu:安八郡": "ogaki",
  "gifu:揖斐郡": "ogaki",
  "gifu:本巣郡": "motosu",
  "gifu:山県郡": "yamagata",
  "gifu:武儀郡": "seki",
  "gifu:加茂郡": "minokamo",
  "gifu:可児郡": "kani",
  "gifu:土岐郡": "toki",
  "gifu:恵那郡": "ena",
  "gifu:中津川郡": "nakatsugawa",
  "gifu:益田郡": "gero",
  "gifu:大野郡": "hida",
  "gifu:吉城郡": "hida",
  "gifu:郡上郡": "gujo",
  "gifu:飛騨郡": "hida",
  // ─── 三重県 ───
  "mie:桑名郡": "kuwana",
  "mie:員弁郡": "inabe",
  "mie:三重郡": "yokkaichi",
  "mie:鈴鹿郡": "suzuka",
  "mie:河芸郡": "tsu",
  "mie:安芸郡": "tsu",
  "mie:一志郡": "tsu",
  "mie:飯南郡": "matsusaka",
  "mie:多気郡": "matsusaka",
  "mie:渡会郡": "ise",
  "mie:度会郡": "ise",
  "mie:志摩郡": "shima",
  "mie:南牟婁郡": "kumano",
  "mie:北牟婁郡": "owase",
  "mie:名賀郡": "iga",
  "mie:阿山郡": "iga",
  // ─── 静岡県 ───
  "shizuoka:浜名郡": "hamamatsu",
  "shizuoka:引佐郡": "hamamatsu",
  "shizuoka:周智郡": "kakegawa",
  "shizuoka:小笠郡": "kikugawa",
  "shizuoka:榛原郡": "makinohara",
  "shizuoka:志太郡": "fujieda",
  "shizuoka:庵原郡": "shizuoka",
  "shizuoka:安倍郡": "shizuoka",
  "shizuoka:富士郡": "fuji",
  "shizuoka:駿東郡": "numazu",
  "shizuoka:田方郡": "izunokuni",
  "shizuoka:賀茂郡": "shimoda",
  "shizuoka:佐野郡": "fuji",
  "shizuoka:富士川郡": "fuji",
};
